export const projects = [
    {
        id: 1,
        title: 'Carwash System',
        description: 'Carwash System es una plataforma compuesta por 28 módulos para la gestión administrativa de un autolavado, desarrollada como proyecto de investigación aplicada. Integra áreas como marketing, operaciones, finanzas e inventario en una arquitectura modular orientada a interfaces, facilitando escalabilidad, mantenimiento y evolución funcional.',
        image: '/images/projects/carwash_preview.png',
        thumbnail: '/images/projects/carwash_thumbnail.png',
        url: 'carwash-system',
        technologies: ['Next.js', 'Material UI', 'Typescript'],
        date: '2024-01-01',
    },
    {
        id: 2,
        title: 'School Management',
        description: 'School Management es una plataforma administrativa web para educación primaria, construida con stack MERN para centralizar procesos académicos y operativos. El sistema gestiona boletines, representantes, asignación y promoción de grado, docentes y evaluaciones en una experiencia intuitiva orientada a la adopción institucional.',
        image: '/images/projects/schoolManagement_preview.png',
        thumbnail: '/images/projects/schoolManagement_thumbnail.png',
        url: 'school-management',
        technologies: ['React', 'Express', 'MongoDB', 'Node.js'],
        date: '2024-01-01',
    },
    {
        id: 3,
        title: 'Musicband',
        description: 'Musicband es una aplicación para la gestión de repertorios en bandas musicales, diseñada para reducir la repetición de canciones en presentaciones en vivo y optimizar la planificación de setlists. Incluye control de usuarios, gestión de seguridad y una interfaz construida con MERN para una operación ágil y confiable.',
        image: '/images/projects/musicband_preview.png',
        thumbnail: '/images/projects/musicband_thumbnail.png',
        url: 'musicband',
        technologies: ['React', 'Express', 'MongoDB', 'Node.js'],
        date: '2024-01-01',
    },
    {
        id: 4,
        title: 'TaskBot',
        description: 'TaskBot es una aplicación móvil de gestión de tareas desarrollada con Expo y React Native en frontend, junto con Express y MySQL en backend. Incorpora clasificación de tareas, seguimiento por pasos, estadísticas, notificaciones configurables y apoyo con IA para sugerencias de mejora, con sincronización por cuenta en tiempo real.',
        image: '/images/projects/taskbot_preview.png',
        thumbnail: '/images/projects/taskbot_thumbnail.png',
        url: 'taskbot',
        technologies: ['React', 'Node.js', 'Express', 'MongoDB'],
        date: '2024-01-01',
    },
    {
        id: 5,
        title: 'ChatApp',
        description: 'ChatApp es una solución de mensajería privada en tiempo real que permite la comunicación entre usuarios mediante salas privadas y canales seguros. Fue desarrollada con Express y WebSockets, priorizando baja latencia, simplicidad de uso y una experiencia de interacción fluida.',
        image: '/images/projects/chatapp_preview.png',
        thumbnail: '/images/projects/chatapp_thumbnail.png',
        url: 'chatapp',
        technologies: ['React', 'Express', 'Socket.io', 'Node.js'],
        date: '2024-01-01',
    },
    {
        id: 6,
        title: 'Weather App',
        description: 'Weather App es una aplicación web enfocada en la consulta del clima en tiempo real mediante integración con APIs meteorológicas. El proyecto consolida consumo de servicios externos, procesamiento de respuestas y presentación clara de datos para ofrecer información útil y actualizada al usuario.',
        image: '/images/projects/wheatherapp_preview.png',
        thumbnail: '/images/projects/wheatherapp_thumbnail.png',
        url: 'weather-app',
        technologies: ['React', 'TypeScript', 'API Integration'],
        date: '2024-01-01',
    },
    {
        id: 7,
        title: 'ERP Diagram',
        description: 'ERP Diagram es un proyecto de análisis y diseño de software que documenta de forma integral un sistema administrativo mediante más de 100 diagramas, incluyendo casos de uso, secuencias, actividades y organigramas. Este trabajo fortaleció competencias en levantamiento de requerimientos, modelado de procesos y diseño de soluciones orientadas al negocio.',
        image: '/images/projects/erpDiagram_preview.png',
        thumbnail: '/images/projects/erpDiagram_thumbnail.png',
        url: 'erp-diagram',
        technologies: ['Next.js', 'TypeScript', 'Material UI'],
        date: '2024-01-01',
    },
    {
        id: 8,
        title: 'Bicycles Web Design',
        description: 'Bicycles Web Design representa el diseño integral de una landing page en Figma, enfocada en jerarquía visual, teoría del color, distribución de márgenes y equilibrio de contenido. El proyecto permitió validar decisiones de UI/UX sobre una estructura completa de secciones orientada a claridad y conversión.',
        image: '/images/projects/bicyclesWebDesign_preview.png',
        thumbnail: '/images/projects/bicyclesWebDesign_thumbnail.png',
        url: 'bicycles-web-design',
        technologies: ['React', 'CSS', 'Responsive Design'],
        date: '2024-01-01',
    },
] 

export const certificates = [
    {
        id: 1,
        title: 'Ethical Hacking',
        image: '/images/certificates/ethical-hacking-certificate.png',
        date: '2024-01-01',
        issuer: 'Cisco',
    },
    {
        id: 2,
        title: 'Java',
        image: '/images/certificates/java-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 3,
        title: 'PHP',
        image: '/images/certificates/php-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 4,
        title: 'React',
        image: '/images/certificates/react-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 5,
        title: 'Node.js',
        image: '/images/certificates/nodejs-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 6,
        title: 'JavaScript',
        image: '/images/certificates/javascript-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 7,
        title: 'CSS',
        image: '/images/certificates/css-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
    {
        id: 8,
        title: 'HTML',
        image: '/images/certificates/html-certificate.png',
        date: '2024-01-01',
        issuer: 'Oracle',
    },
]